# Generated by Django 3.1 on 2020-09-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20200909_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
    ]
