# Generated by Django 3.0.8 on 2020-08-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='product',
            new_name='item',
        ),
    ]
