# Generated by Django 3.0.8 on 2020-08-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200820_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_level',
            field=models.CharField(default='Обычный', max_length=20),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.Role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='ChangeOwnerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_item', models.DateTimeField(blank=True, null=True)),
                ('sell_item', models.DateTimeField(blank=True, null=True)),
                ('change_owner_list', models.ManyToManyField(blank=True, to='item.User')),
                ('item_id', models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
            options={
                'verbose_name': 'change owner list',
                'verbose_name_plural': 'changes owner list',
            },
        ),
    ]
