# Generated by Django 3.0.8 on 2020-08-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200820_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeownerlist',
            old_name='change_owner_list',
            new_name='user',
        ),
    ]
