version: "3.3"

services:
    nginx:
        build: ./web
        ports:
            - "127.0.0.1:8080:80"
    api:
        build: ./api
        container_name: django_api
        ports:
            - "8000:8000"
        