# Generated by Django 3.1 on 2020-09-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20200909_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title',
        ),
    ]
