export const PAGE_TEXT = {
    'title': 'Создание предмета: ',
    'item_name_field': 'Название предмета',
    'item_price_field': 'Цена предмета',
    'item_description_field': 'Описание',
    'item_level_field': 'Уровень',
    'item_category_field': 'Категория',
    'item_sub_category_field': 'Подкатегория',
    'item_tags_field': 'Теги',
    'create_category': 'Создать категорию',
    'create_sub_category': 'Создать подкатегорию',
    'or_select': 'Или выбрать',
    'create_category_placeholder': 'Название категории',
    'create_sub_category_placeholder': 'Название подкатегории',
    'create_tag': '+',
    'create_tag_button': 'создать',
}